#!/usr/bin/env bash
echo "1. Create a virtual machine with docker-machine using the virtualbox driver, and named Char:"
echo "______________________________________________"
echo "COMMAND: docker-machine create --driver virtualbox Char"
echo "______________________________________________"
docker-machine create --driver virtualbox Char
