#!/usr/bin/env bash

Char=$(docker-machine ip Char)
echo "______________________________________________"
echo "6. Launch an nginx container, available on Docker Hub, as a background task. It
should be named overlord, be able to restart on its own, and have its 80 port
attached to the 5000 port of Char. You can check that your container functions
properly by visiting
http://<ip-de-char>:5000 on your web browser."
echo "______________________________________________"
echo "COMMAND: docker container run -dp 5000:80 --name overlord --restart always nginx"
echo "______________________________________________"
echo "ALTERNATIVE: docker container run -dp $Char:5000:80 --name overlord --restart always nginx"
echo "______________________________________________"
docker container run -dp $Char:5000:80 --name overlord --restart always nginx
