#!/usr/bin/env bash

echo "______________________________________________"
echo "12. Launch a mysql container as a background task. It should be able to restart on its
own in case of error, and the root password of the database should be Kerrigan.
You will also make sure that the database is stored in the hatchery volume, that
the container directly creates a database named zerglings, and that the container
itself is named spawning-pool. "
echo "______________________________________________"
echo "COMMAND: 
docker container run -e MYSQL_USER="root" -e MYSQL_ROOT_PASSWORD="Kerrigan" -e MYSQL_DATABASE="zerglings" -v hatchery:/var/lib/mysql --restart
=on-failure -d --name spawning-pool mysql --default-authentication-plugin=mysql_native_password"
echo "______________________________________________"
echo "ALTERNATIVE: "
echo "______________________________________________"
echo "NOTES: To make sure everything is ok and running
-> docker exec -it spawning-pool mysql -p

Write password to check it is correct and check databases with command:
mysql> SHOW DATABASES;

There it is!

This might need to be run if Wordpress doesn't connect properly (later):
mysql>ALTER USER 'root' IDENTIFIED WITH mysql_native_password BY 'Kerrigan';
"
echo "______________________________________________"
docker container run -e MYSQL_ROOT_PASSWORD="Kerrigan" -e MYSQL_DATABASE="zerglings" -v hatchery:/var/lib/mysql --restart=on-failure -d --name spawning-pool mysql --default-authentication-plugin=mysql_native_password
