#!/usr/bin/env bash

echo "______________________________________________"
echo "15. Launch a phpmyadmin container as a background task. It should be named roach-warden,
its 80 port should be bound to the 8081 port of the virtual machine and it should
be able to explore the database stored in the spawning-pool container. "
echo "______________________________________________"
echo "COMMAND: docker container run -d --name roach-warden --link spawning-pool:db -p 8081:80 phpmyadmin/phpmyadmin"
echo "______________________________________________"
echo "ALTERNATIVE: "
echo "______________________________________________"
echo "NOTES: Link in this one needs db = database. Without it it doesn't work. username root password Kerrigan."
echo "______________________________________________"
docker container run -d --name roach-warden --link spawning-pool:db -p 8081:80 phpmyadmin/phpmyadmin
