#!/usr/bin/env bash

echo "______________________________________________"
echo "18. Relaunch the overlord container. "
echo "______________________________________________"
echo "COMMAND: docker container restart overlord"
echo "______________________________________________"
echo "ALTERNATIVE: "
echo "______________________________________________"
echo "NOTES: "
echo "______________________________________________"
docker container restart overlord