#!/usr/bin/env bash

echo "______________________________________________"
echo "19. Launch a container name Abathur. It will be a Python container, 2-slim version,
its /root folder will be bound to a HOME folder on your host, and its 3000 port
will be bound to the 3000 port of your virtual machine.
You will personalize this container so that you can use the Flask micro-framework
in its latest version. You will make sure that an html page displaying "Hello World"
with <h1> tags can be served by Flask. You will test that your container is
properly set up by accessing, via curl or a web browser, the IP address of your
virtual machine on the 3000 port.
You will also list all the necessary commands in your repository. "
echo "______________________________________________"
echo "COMMAND: These commands need to be run one by one in shell:
docker container run --name Abathur -p 3000:3000 -v ~/:/root -dit python:2-slim
docker container exec Abathur pip install --upgrade pip flask
echo 'from flask import Flask\napp = Flask(__name__)\n\n@app.route(\"/\")\ndef hello_world():\n    return \"<h1>Hello, World</h1>\"' > ~/hello.py
docker container exec -e FLASK_APP=/root/hello.py Abathur python -m flask run --host=$Char --port=3000
"
echo "______________________________________________"
echo "ALTERNATIVE: "
echo "______________________________________________"
echo "NOTES: run these commands one by one in shell:
docker container run --name Abathur -p 3000:3000 -v ~/:/root -dit python:2-slim
- this one creates the Abathur and bind mounds home folder of host to containers /root folder
docker container exec Abathur pip install --upgrade pip flask
- updates pip and installs flask
echo 'from flask import Flask\napp = Flask(__name__)\n\n@app.route(\"/\")\ndef hello_world():\n    return \"<h1>Hello, World</h1>\"' > ~/hello.py
- creates hello.py flask app
docker container exec -e FLASK_APP=/root/hello.py Abathur python -m flask run --host=0.0.0.0 --port=3000
- runs FLASK hello.py app and uses host ip and port 3000
"
echo "______________________________________________"
