#!/usr/bin/env bash

echo "______________________________________________"
echo "21. Create another virtual machine with docker-machine using the virtualbox driver,
and name it Aiur. "
echo "______________________________________________"
echo "COMMAND: docker-machine create --driver virtualbox Aiur"
echo "______________________________________________"
echo "ALTERNATIVE: "
echo "______________________________________________"
echo "NOTES: "
echo "______________________________________________"
docker-machine create --driver virtualbox Aiur