#!/usr/bin/env bash

echo "______________________________________________"
echo "23. Create an overlay-type internal network that you will name overmind. "
echo "______________________________________________"
echo "COMMAND: docker network create -d overlay overmind"
echo "______________________________________________"
echo "ALTERNATIVE: "
echo "______________________________________________"
echo "NOTES:
https://docs.docker.com/engine/reference/commandline/network/"
echo "______________________________________________"
docker network create -d overlay overmind