#!/usr/bin/env bash

echo "______________________________________________"
echo "24. Launch a rabbitmq SERVICE that will be named orbital-command. You should
define a specific user and password for the RabbitMQ service, they can be whatever
you want. This service will be on the overmind network. "
echo "______________________________________________"
echo "COMMAND: "
echo "______________________________________________"
echo "ALTERNATIVE: "
echo "______________________________________________"
echo "NOTES: "
echo "______________________________________________"
