#!/usr/bin/env bash

echo "______________________________________________"
echo "25. List all the services of the local swarm. "
echo "______________________________________________"
echo "COMMAND: docker service ls"
echo "______________________________________________"
echo "ALTERNATIVE: "
echo "______________________________________________"
echo "NOTES: This command lists services are running in the swarm.
https://docs.docker.com/engine/reference/commandline/service_ls/"
echo "______________________________________________"
docker service ls