#!/usr/bin/env bash

echo "______________________________________________"
echo "27. Get the real-time logs of one the tasks of the engineering-bay service. "
echo "______________________________________________"
echo "COMMAND: "
echo "______________________________________________"
echo "ALTERNATIVE: "
echo "______________________________________________"
echo "NOTES: "
echo "______________________________________________"
docker service logs -f engineering-bay