#!/usr/bin/env bash

echo "______________________________________________"
echo "28. ... Damn it, a group of zergs is attacking orbital-command, and shutting down
the engineering-bay service won’t help at all... You must send a troup of Marines
to eliminate the intruders. Launch a 42school/marine-squad in two replicas,
and make sure that the service works properly (see the documentation provided
at hub.docker.com). This service will be named... marines and will be on the
overmind network. "
echo "______________________________________________"
echo "COMMAND: docker service create --replicas 2 -e OC_USERNAME=john -e OC_PASSWD=rabbit --name marines --network overmind 42school/marine-squad"
echo "______________________________________________"
echo "ALTERNATIVE: "
echo "______________________________________________"
echo "NOTES: "
echo "______________________________________________"
docker service create --replicas 2 -e OC_USERNAME=john -e OC_PASSWD=rabbit --name marines --network overmind 42school/marine-squad