#!/usr/bin/env bash

echo "______________________________________________"
echo "29. Display all the tasks of the marines service. "
echo "______________________________________________"
echo "COMMAND: docker service ps marines"
echo "______________________________________________"
echo "ALTERNATIVE: "
echo "______________________________________________"
echo "NOTES: "
echo "______________________________________________"
docker service ps marines