#!/usr/bin/env bash

echo "______________________________________________"
echo "31. Force quit and delete all the services on the local swarm, in one command. "
echo "______________________________________________"
echo "COMMAND: docker service rm -f $(docker service ls -q)"
echo "______________________________________________"
echo "ALTERNATIVE: "
echo "______________________________________________"
echo "NOTES: "
echo "______________________________________________"
docker service rm $(docker service ls -q)