#!/usr/bin/env bash

echo "______________________________________________"
echo "32. Force quit and delete all the containers (whatever their status), in one command."
echo "______________________________________________"
echo "COMMAND: "
echo "______________________________________________"
echo "ALTERNATIVE: "
echo "______________________________________________"
echo "NOTES: "
echo "______________________________________________"
docker container rm -f $(docker container ls -a -q)