#!/usr/bin/env bash

echo "______________________________________________"
echo "33. Delete all the container images stored on the Char virtual machine, in one command
as well. "
echo "______________________________________________"
echo "COMMAND: docker image rm -f $(docker images -a -q)"
echo "______________________________________________"
echo "ALTERNATIVE: "
echo "______________________________________________"
echo "NOTES:
docker images -a -q = get all image ids to delete
 "
echo "______________________________________________"
docker image rm -f $(docker images -a -q)