#!/usr/bin/env bash

echo "______________________________________________"
echo "34. Delete the Aiur virtual machine without using rm -rf. "
echo "______________________________________________"
echo "COMMAND: docker-machine rm -y Aiur"
echo "______________________________________________"
echo "ALTERNATIVE: "
echo "______________________________________________"
echo "NOTES: with y-flag it assumes automatic yes,
with f-flag it forces and also automates yes"
echo "______________________________________________"
docker-machine rm -y Aiur